config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :beer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  end

app/controllers/beer_controller.rb
class BeerController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

    def index
        @beers = Beer.all
      end
    
      def new
        @beer = Beer.new
      end
    
      def create
        @beer = Beer.new(beer_params)
        @beer.save
        redirect_to beer_path(@beer)
      end
    
      def show
      end
    
      def edit
      end
    
      def update
        @beer.update(beer_params)
        redirect_to beer_path(@beer)
      end
    
      def destroy
        @beer.destroy
        redirect_to beers_path
      end

      private
    
      def set_beer
        @beer = Beer.find(params[:id])
      end

      def restaurant_params
        params.require(:restaurant).permit(:name, :rating, :producer, :price, :type)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beer_helper.rb
module BeerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/beer/_form.html.erb
<%= simple_form_for beer do |b| %>
    <%= b.input :name %>
    <%= b.input :rating %>
    <%= b.input :price %>
    <%= b.input :producer %>
    <%= b.input :type %>
    <%= b.submit %>
  <% end %>

app/views/beer/edit.html.erb
<h1>Edit <%= @beer.name %></h1>

<%= render 'form', beer: @beer %>

app/views/beer/index.html.erb
<h1>Beers</h1>
<ul>
  <% @beers.each do |beer| %>
    <div>
      <li><%= link_to beer.name, beer_path(beer) %></li>
    </div>
  <% end %>
</ul>
<%= link_to 'Créer une bière', new_beer_path %>

app/views/beer/new.html.erb
<h1>Creer une bière</h1>

<%= render 'form', beer: @beer %>

app/views/beer/show.html.erb
<h1><%= @beer.name %></h1>
<p>Cette bière a une note moyenne de <%= @beer.rating %></p>

<%= link_to "Editer une bière", edit_beer_path(@beer) %>
<%= link_to "Supprimer #{@beer.name}", beer_path(@beer), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetDubucheFitamant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>HomePage</h1>
<%= link_to 'bières', beer_index_path %>